language: r
cache: packages
r:
  - release
#  - oldrel
#  - devel

r_packages:
  - covr
  - lintr
  - drat
  - RPushbullet

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
  - Rscript -e 'RPushbullet::pbPost("note",
                                    "It's alive",
                                    "This was meant to happen",
                                    apikey = Sys.getenv("PUSHBULLET"),
                                    devices = list("ujBMyrjTBZYsjAiVsKnSTs", "ujBMyrjTBZYsjz7O3P0Jl6"))'

