language: r
cache: packages
r:
  - release
#  - oldrel
#  - devel

r_packages:
  - covr
  - drat
  - RPushbullet

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
  - Rscript -e 'RPushbullet::pbPost("note", "A simple title", "Hi", \
        apikey = $PUSHBULLET, \
       devices = list("ujBMyrjTBZYsjAiVsKnSTs", "ujBMyrjTBZYsjz7O3P0Jl6"))'
